# permissions for end users to edit bpfexporters.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: bpfexporter-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: bpfexporter
    app.kubernetes.io/part-of: bpfexporter
    app.kubernetes.io/managed-by: kustomize
  name: bpfexporter-editor-role
rules:
- apiGroups:
  - ebpf.exporter.k8s.aws
  resources:
  - bpfexporters
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ebpf.exporter.k8s.aws
  resources:
  - bpfexporters/status
  verbs:
  - get
